name: Service Repo Build and Deploy (Docker Hub)

on:
  workflow_call:
    inputs:
      SERVICES:
        type: string
        description: Comma-separated string of services (e.g. "susunjadwal/susunjadwal-backend-stg")
        required: true
      INSTANCE:
        type: string
        description: Which instance is the deploy target (Instance Name)
        required: true
      IMAGE:
        type: string
        description: Name of the image to build
        required: true
      DOCKERHUB_USER:
        type: string
        description: User account for the Docker Hub registry
        required: true
      PLATFORMS:
        type: string
        description: Comma separated (no spaces) list of target platforms to build for
        default: linux/amd64
      IMAGE_TAG:
        type: string
        description: Image tag name (either stable or latest, but you can also use your own tags)
        default: latest
    secrets:
      GH_TOKEN:
        description: GitHub token to trigger deployments on Central Infra
        required: true
      DOCKERHUB_TOKEN:
        description: The Docker Hub access token
        required: true

jobs:
  build_and_push:
    name: Build and Push Image to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ inputs.DOCKERHUB_USER }}/${{ inputs.IMAGE }}:${{ inputs.IMAGE_TAG }}
          platforms: ${{ inputs.PLATFORMS }}

  central_infra_deploy:
    name: Trigger Deployment on Central Infra
    needs: [build_and_push]
    runs-on: ubuntu-22.04
    steps:
      - run: |
          REPO_OWNER=RistekCSUI
          REPO_NAME=infra
          EVENT_TYPE=trigger-workflow

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
            -d "{\"event_type\": \"$EVENT_TYPE\", \"client_payload\": {\"SERVICES\": \"${{ inputs.SERVICES }}\", \"INSTANCE\": \"${{ inputs.INSTANCE }}\"}}"
